# {dotfiles}/bombadil.toml

# Path to your dotfiles relative to your $HOME directory
dotfiles_dir = "dotfiles"

[settings]
# An array of toml files paths containing the variables to inject in your templatized dotfiles
# You can have multiple var files as long as variable names does not colide.
vars = [ "vars.toml" ]

# An array of post install shell commands
# posthooks = [ "sway reload" ]

[settings.dots]

# A dot entry representing a symlink, `source` is relative to `dotfiles_dir`
# and `target` shall be relative to $HOME directory or absolute.
hypr = { source = "hypr", target = ".config/hypr" }
foot = { source = "foot", target = ".config/foot" }
pacdef = { source = "pacdef/pacdef.yaml", target = ".config/pacdef/pacdef.yaml" }
starship = { source = "starship.toml", target = ".config/starship.toml" }
waybar = { source = "waybar", target = ".config/waybar" }
wofi = { source = "wofi", target = ".config/wofi" }
zsh = { source = "zsh/zshrc", target = ".zshrc" }
mako = { source = "mako", target = ".config/mako" }

