# Path to your dotfiles relative to your $HOME directory
dotfiles = "dotfiles"

# A dot entry representing a symlink, `source` is relative to `dotfiles_dir`
# and `target` shall be relative to $HOME directory or absolute.
dots = [
	{ source = "hypr", target = ".config/hypr" },
	{ source = "foot", target = ".config/foot" },
	{ source = "kitty", target = ".config/kitty" },
	{ source = "metapac", target = ".config/metapac" },
	{ source = "starship.toml", target = ".config/starship.toml" },
	{ source = "waybar", target = ".config/waybar" },
	{ source = "wofi", target = ".config/wofi" },
	{ source = "walker", target = ".config/walker" },
	{ source = "zsh/zshrc", target = ".zshrc" },
	{ source = "mako", target = ".config/mako" },
	{ source = "fuzzel", target = ".config/fuzzel" },
	{ source = "fnott", target = ".config/fnott" },
	{ source = "swaync", target = ".config/swaync" },
	{ source = "wleave", target = ".config/wleave" },
	{ source = "micro", target = ".config/micro" },
	{ source = "zed", target = ".config/zed" },
	{ source = "gtk-settings/settings.ini", target = ".config/gtk-3.0/settings.ini" },
	{ source = "gtk-settings/gtkrc-2.0", target = ".gtkrc-2.0" },
	{ source = "gtk-settings/xsettingsd.conf", target = ".config/xsettingsd/xsettingsd.conf" },
]

