# Path to your dotfiles relative to your $HOME directory
dotfiles = "dotfiles"

# A dot entry representing a symlink, `source` is relative to `dotfiles_dir`
# and `target` shall be relative to $HOME directory or absolute.
dots = [
    { source = "environment", target = ".config/environment.d" },
    { source = "fnott", target = ".config/fnott" },
    { source = "foot", target = ".config/foot" },
    { source = "fuzzel", target = ".config/fuzzel" },
    { source = "gtk-settings/gtkrc-2.0", target = ".gtkrc-2.0" },
    { source = "gtk-settings/settings.ini", target = ".config/gtk-3.0/settings.ini" },
    { source = "gtk-settings/xsettingsd.conf", target = ".config/xsettingsd/xsettingsd.conf" },
    { source = "hypr", target = ".config/hypr" },
    { source = "ironbar", target = ".config/ironbar" },
    { source = "kitty", target = ".config/kitty" },
    { source = "mako", target = ".config/mako" },
    { source = "metapac", target = ".config/metapac" },
    { source = "micro", target = ".config/micro" },
    { source = "starship.toml", target = ".config/starship.toml" },
    { source = "swaync", target = ".config/swaync" },
    { source = "systemd", target = ".config/systemd/user" },
    { source = "uwsm", target = ".config/uwsm" },
    { source = "walker", target = ".config/walker" },
    { source = "waybar", target = ".config/waybar" },
    { source = "wireplumber", target = ".config/wireplumber" },
    { source = "wleave", target = ".config/wleave" },
    { source = "wofi", target = ".config/wofi" },
    { source = "zed", target = ".config/zed" },
    { source = "zsh/zshrc", target = ".zshrc" },
]
