format = """
$username\
$hostname\
$os\
$git_branch\
$git_status\
$git_metrics\
$package\
$gradle\
$nodejs\
$rust\
$golang\
$kotlin\
$java\
$fill\
$cmd_duration$jobs$time
$sudo$directory$character"""

[os]
format = "$symbol "
disabled = false

[username]
show_always = true
format = "[$user]($style)"

[hostname]
ssh_only = false
ssh_symbol = " "
format = " on [$ssh_symbol$hostname]($style) "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[time]
disabled = false
format = " [  $time]($style)"

[cmd_duration]
format = "[󰔛 $duration]($style)"

[directory]
read_only = " 󰌾"
truncate_to_repo = false
truncation_length = 5
truncation_symbol = "…/"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = "[ ](fg:#1793d1)"
Artix = " "
CentOS = " "
Debian = "[ ](fg:#d70751)"
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = "[ ](fg:#51a2da)"
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = "[ ](fg:#ff5722)"
Unknown = " "
Void = " "
Windows = "󰍲 "

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "
