
arch = [
    "amd-ucode",
    "archlinux-wallpaper",
    "base",
    "blueman",
    "bluez",
    "cronie",
    "cups",
    "efibootmgr",
    "evtest",
    "eza",
    "fastfetch",
    "flatpak",
    "foot",
    "fzf",
    "git",
    "go",
    "greetd",
    "greetd-regreet",
    "greetd-tuigreet",
    "gvfs",
    "kitty",
    "kitty-terminfo",
    "less",
    "libreoffice-still",
    "libva-utils",
    "linux",
    "linux-firmware",
    "man-db",
    "man-pages",
    "metapac-bin",
    "micro",
    "networkmanager",
    "noto-fonts",
    "ntp",
    "opendoas",
    "openssh",
    "otf-comicshanns-nerd",
    "otf-font-awesome",
    "otf-monaspace-nerd",
    "pipewire-pulse",
    "pkgfile",
    "plocate",
    "plymouth",
    "rocm-smi-lib",
    "rsync",
    "rust",
    "smartmontools",
    "solaar",
    "speech-dispatcher",
	"splix",
    "sshfs",
    "starship",
    "sxiv",
    "system-config-printer",
    "wireguard-tools",
    "yay",
    "zoxide",
    "zsh",
    "zsh-autosuggestions",
    "zsh-syntax-highlighting",
]
flatpak= [
"com.github.tchx84.Flatseal",
"com.mikeasoft.pied"
]
