arch = [
    "code",
    "composer",
	"dbgate-bin",
    "dbus-glib",
    "docker",
    "docker-compose",
    "enchant",
    "fnm-bin",
    "lazygit",
    "python-pip",
    "woff-fira-code",
    "zed",
    "php-gd",
    "qt5-tools",
    "sublime-text-4",
]
