arch = [
    "code",
    "composer",
    "dbeaver",
    "dbus-glib",
    "docker",
    "docker-compose",
    "enchant",
    "google-cloud-cli",
    "lazygit",
    "python-pip",
    "woff-fira-code",
    "zed",
]
