arch = [
    "gamemode",
    "heroic-games-launcher-bin",
    "linux-zen",
    "lutris",
    "r2modman-bin",
    "steam-devices-git",
]
flatpak = [
    "com.valvesoftware.Steam",
    "org.freedesktop.Platform.VulkanLayer.MangoHud",
]
