arch = [
	"arc-gtk-theme",
	"arc-icon-theme",
	"beautyline",
	"cliphist",
	"ffmpegthumbnailer",
	"file-roller",
	"fuzzel",
	"grimblast-git",
	"hypridle",
	"hyprland",
	"hyprlock",
	"hyprpaper",
	"hyprpicker",
	"ironbar-git",
	"ksshaskpass",
	"kwallet",
	"kwallet-pam",
	"kwalletmanager",
	"mousepad",
	"nemo",
	"network-manager-applet",
	"networkmanager-dmenu-git",
	"nwg-look",
	"pamixer",
	"pavucontrol",
	"polkit-kde-agent",
	"qt5-wayland",
	"qt5ct",
	"qt6ct",
	"ristretto",
	"satty",
	"swaync",
	"webp-pixbuf-loader",
	"wl-clipboard",
	"xarchiver",
	"xdg-desktop-portal-gtk",
	"xdg-desktop-portal-hyprland",
	"uwsm",
]
