arch = [
    "arc-gtk-theme",
    "arc-icon-theme",
    "beautyline",
    "cliphist",
    "dex",
    "ffmpegthumbnailer",
    "fnott",
    "fuzzel",
    "grimblast-git",
    "hypridle",
    "hyprland",
    "hyprlock",
    "hyprpaper",
    "hyprpicker",
    "ksshaskpass",
    "kvantum",
    "kwallet-pam",
    "kwallet5",
    "kwalletmanager",
    "mousepad",
    "nemo",
    "network-manager-applet",
    "nwg-look",
    "pamixer",
    "pavucontrol",
    "polkit-kde-agent",
    "qt5-wayland",
    "qt5ct",
    "qt6ct",
    "ristretto",
    "waybar",
    "webp-pixbuf-loader",
    "wl-clipboard",
    "wleave-git",
    "xarchiver",
    "xdg-desktop-portal-gtk",
    "xdg-desktop-portal-hyprland",
]
