arch = [
    "arc-gtk-theme",
    "arc-icon-theme",
    "beautyline",
    "cliphist",
    "dex",
    "ffmpegthumbnailer",
	"file-roller",
    "fuzzel",
	"gnome-keyring",
    "grimblast-git",
    "hypridle",
    "hyprland",
    "hyprlock",
    "hyprpaper",
    "hyprpicker",
    "mousepad",
    "nemo",
    "network-manager-applet",
    "networkmanager-dmenu-git",
    "nwg-look",
    "pamixer",
    "pavucontrol",
    "polkit-kde-agent",
    "qt5-wayland",
    "qt5ct",
    "qt6ct",
    "ristretto",
	"satty",
	"seahorse",
	"swaync",
    "waybar",
    "webp-pixbuf-loader",
    "wl-clipboard",
    "xarchiver",
    "xdg-desktop-portal-gtk",
    "xdg-desktop-portal-hyprland",
    "uwsm",
]
