arch = [
	"bind",
	"claws-mail",
	"filezilla",
	"librewolf-bin",
	"mullvad-browser-bin",
	"mullvad-vpn-bin",
	"syncthing",
	"thunderbird",
	"transmission-gtk",
	"vivaldi",
	"vivaldi-ffmpeg-codecs",
	"whois",
	"zen-browser-bin",
]
