arch = [
    "bluedevil",
    "breeze",
    "breeze-gtk",
    "breeze-plymouth",
    "discover",
    "dolphin",
    "drkonqi",
    "flatpak-kcm",
    "kactivitymanagerd",
    "kde-cli-tools",
    "kde-gtk-config",
    "kdecoration",
    "kdeplasma-addons",
    "kgamma",
    "kglobalacceld",
    "kinfocenter",
    "kmenuedit",
    "kpipewire",
    "krdp",
    "konsole",
    "kscreen",
    "kscreenlocker",
    "ksshaskpass",
    "ksystemstats",
    "kwallet-pam",
    "kwayland",
    "kwin",
    "kwin-effects-forceblur",
    "kwrited",
    "layer-shell-qt",
    "libkscreen",
    "libksysguard",
    "libplasma",
    "milou",
    "ocean-sound-theme",
    "oxygen",
    "oxygen-sounds",
    "plasma-activities",
    "plasma-activities-stats",
    "plasma-browser-integration",
    "plasma-desktop",
    "plasma-disks",
    "plasma-firewall",
    "plasma-integration",
    "plasma-nm",
    "plasma-pa",
    "plasma-sdk",
    "plasma-systemmonitor",
    "plasma-thunderbolt",
    "plasma-vault",
    "plasma-welcome",
    "plasma-workspace",
    "plasma-workspace-wallpapers",
    "plasma5support",
    "plymouth-kcm",
    "powerdevil",
    "print-manager",
    "qqc2-breeze-style",
    "sddm-kcm",
    "spectacle",
    "systemsettings",
    "wacomtablet",
    "xdg-desktop-portal-kde",
]
