arch = [
    "blender",
    "btop",
    "dosfstools",
    "downgrade",
    "glmark2",
    "gparted",
    "hip-runtime-amd",
    "hugo",
    "joplin-appimage",
    "papers",
    "piper",
    "stress",
    "tesseract-data-eng",
    "tesseract-data-fin",
    "tesseract-data-swe",
    "qmk",
    "via-bin",
    "yubikey-personalization-gui",
    "yubioath-desktop",
    "wireguard-vanity-address",
    "xorg-xeyes",
]
flatpak = ["org.dbgate.DbGate"]
