position = "top"

[[start]]
type = "workspaces"

[[start]]
type = "tray"

[[start]]
type = 'sys_info'
format = [
	" {cpu_percent}% {temp_c@CPU}C",
	" {memory_percent}%",
	"󰖡 {load_average_1}",
]

[start.interval]
cpu = 1
disks = 300
memory = 30
networks = 3
temps = 5


[[center]]
type = "focused"
show_icon = true
show_title = true
truncate = "end"

[[end]]
type = "volume"
format = "{icon} {percentage}%"
max_volume = 100

[[end]]
type = "upower"
format = "{percentage}%"

[[end]]
type = "clock"

[[end]]
type = "notifications"
show_count = true
